(defun color-theme-jcp ()
  (interactive)
  (color-theme-install
   '(color-theme-jcp
      ((background-color . "#323339")
      (background-mode . light)
      (border-color . "#5469b6")
      (cursor-color . "#ffe91a")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#5469b6"))))
     (mode-line ((t (:foreground "#ffffff" :background "#4f65b0"))))
     (region ((t (:background "#596982"))))
     (font-lock-builtin-face ((t (:foreground "#87ce69"))))
     (font-lock-comment-face ((t (:foreground "#9365b8"))))
     (font-lock-function-name-face ((t (:foreground "#fc5959"))))
     (font-lock-keyword-face ((t (:foreground "#75d2ff"))))
     (font-lock-string-face ((t (:foreground "#d0706d"))))
     (font-lock-type-face ((t (:foreground"#fd7272"))))
     (font-lock-variable-name-face ((t (:foreground "#fb7070"))))
     (minibuffer-prompt ((t (:foreground "#f5d084" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'color-theme-jcp)