(defun color-theme-jcp-tres ()
  "John is so super cool."
  (interactive)
  (color-theme-install
   '(color-theme-jcp-tres
     ((background-color . "#262721")
      (background-mode . dark)
      (border-color . "#404040")
      (cursor-color . "#63d9ef")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#343836" :background "DarkSalmon"))))
     (region ((t (:background "LightSalmon"))))
     (font-lock-builtin-face ((t (:foreground "#F92572"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-constant-face ((t (:foreground "#FD951F"))))
     (font-lock-function-name-face ((t (:foreground "#A6E22D"))))
     (font-lock-keyword-face ((t (:foreground "#63D9EF"))))
     (font-lock-string-face ((t (:foreground "#E6DB63"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "#2e3436" :background "#e9b96e"))))
     (show-paren-match-face ((t (:foreground "#2e3436" :background "#73d216"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (flymake-errline ((((class color)) (:background "LightPink" :foreground "black"))))
     (flymake-warnline ((((class color)) (:background "LightBlue2" :foreground "black"))))
     )))
(provide 'color-theme-jcp-tres)