(defun holy-fuck ()
  (interactive)
  (color-theme-install
   '(holy-fuck
      ((background-color . "#2a2e32")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#333333" :background "#e2ab55"))))
     (region ((t (:background "#4b5c68"))))
     (font-lock-builtin-face ((t (:foreground "#9ccb8b"))))
     (font-lock-comment-face ((t (:foreground "#9f86ac"))))
     (font-lock-function-name-face ((t (:foreground "#f56766"))))
     (font-lock-keyword-face ((t (:foreground "#70b5ff"))))
     (font-lock-string-face ((t (:foreground "#e88cde"))))
     (font-lock-type-face ((t (:foreground"#f95b58"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'holy-fuck)