(defun color-theme-blobular ()
  (interactive)
  (color-theme-install
   '(color-theme-blobular
      ((backgroun6-color . "#767676")
       (background-mode . light)
       (border-color . "#ffbaa3")
       (cursor-color . "#f0003e")
       (foreground-color . "#ffffff")
       (mouse-color . "black"))
     (fringe ((t (:background "#ffbaa3"))))
     (mode-line ((t (:foreground "#ffffff" :background "#ff9b80"))))
     (region ((t (:background "#9a4942"))))
     (font-lock-builtin-face ((t (:foreground "#94f094"))))
     (font-lock-comment-face ((t (:foreground "#ff947a"))))
     (font-lock-function-name-face ((t (:foreground "#21edd7"))))
     (font-lock-keyword-face ((t (:foreground "#fff266"))))
     (font-lock-string-face ((t (:foreground "#89dee1"))))
     (font-lock-type-face ((t (:foreground"#55cdf7"))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (minibuffer-prompt ((t (:foreground "#72ffda" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'color-theme-blobular)