(defun color-theme-jcp ()
  (interactive)
  (color-theme-install
   '(color-theme-jcp
     ((background-color . "#222222")
      (background-mode . dark)
      (border-color . "#888888")
      (cursor-color . "#ffff40")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#888888"))))
     (mode-line ((t (:foreground "#ffffff" :background "#fa524f"))))
     (region ((t (:background "#596982"))))
     (font-lock-builtin-face ((t (:foreground "#219372"))))
     (font-lock-comment-face ((t (:foreground "#9365b8"))))
     (font-lock-constant-face ((t (:foreground "#8ae234"))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-function-name-face ((t (:foreground "#fc5959"))))
     (font-lock-keyword-face ((t (:foreground "#75d2ff"))))
     (font-lock-string-face ((t (:foreground "#d0706d"))))
     (font-lock-type-face ((t (:foreground"#fd7272"))))
     (font-lock-variable-name-face ((t (:foreground "#fb7070"))))
     (font-lock-warning-face ((t (:bold t :foreground "#f57900"))))
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "#2e3436" :background "#e9b96e"))))
     (show-paren-match-face ((t (:foreground "#2e3436" :background "#73d216"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#f5d084" :bold t))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     )))
(provide 'color-theme-jcp)