(defun color-theme-holy-fuck ()
  (interactive)
  (color-theme-install
   '(color-theme-holy-fuck
      ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#616161")
      (cursor-color . "#f0a800")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#616161"))))
     (mode-line ((t (:foreground "#ffffff" :background "#d04e4e"))))
     (region ((t (:background "#3a693a"))))
     (font-lock-builtin-face ((t (:foreground "#ff7070"))))
     (font-lock-comment-face ((t (:foreground "#8f6a66"))))
     (font-lock-function-name-face ((t (:foreground "#0080FF"))))
     (font-lock-keyword-face ((t (:foreground "#fcbc8d"))))
     (font-lock-number-face ((t (:foreground "#d000FF"))))
     (font-lock-string-face ((t (:foreground "#83FF52"))))
     (font-lock-type-face ((t (:foreground"#81b0e4"))))
     (font-lock-variable-name-face ((t (:foreground "#94C9FF"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'color-theme-holy-fuck)